kind: wasmer.io/App.v0

owner: ilhammaulanaakbar
name: etalase-pelatihan-masyarakat

package: .

env:
  PUBLIC_STORAGE_PATH: "/app/public/storage"

volumes:
  - name: public-uploads
    mount: /app/public/storage

locality:
  regions:
    - us-socal1

scaling:
  mode: single_concurrency