name: etalase-pelatihan-masyarakat
owner: ilhammaulanaakbar
package: .
locality:
  regions:
  - fr-roub1
env:
  PUBLIC_STORAGE_PATH: /app/public/storage
volumes:
- name: public-uploads
  mount: /app/public/storage
scaling:
  mode: single_concurrency
kind: wasmer.io/App.v0